import {
  TaskFromSupabase,
  TimeStage,
  Energy,
  AgingStatus,
} from "../types/task";

export function getTask(data: Partial<TaskFromSupabase>): TaskFromSupabase {
  const now = new Date().toISOString();

  return {
    id: crypto.randomUUID(),
    title: "",
    description: "",
    timestage: "queue" as TimeStage,
    stage_entry_date: now,
    assignee: "",
    list_id: null,
    aging_status: "normal" as AgingStatus,
    priority: "medium",
    energy: "medium" as Energy,
    location: null,
    story_id: null,
    labels: [],
    show_in_time_box: true,
    show_in_list: true,
    show_in_calendar: false,
    icon: "blue",
    highlighted: false,
    created_at: now,
    updated_at: now,
    created_by: "",
    schedule_date: null,
    schedule_time: null,
    lead_days: 0,
    lead_hours: 0,
    duration_days: 0,
    duration_hours: 0,
    recurring: null,
    status: null,
    recurring_interval: null,
    week_days: null,
    workdays_only: false,
    ends_type: "never",
    ends_date: null,
    ends_after_occurrences: null,
    alarm_enabled: false,
    ...data,
  };
}
